[green_agent]
agentbeats_id = "019c178a-0f6f-7852-9fc8-f2aa84ebdf56"
env = {}

[[participants]]
agentbeats_id = "019c1788-faf4-7170-9953-a84321132e16"
name = "agent"
env = {GOOGLE_API_KEY = "${GOOGLE_API_KEY}", LLM_MODEL="gemini-2.5-pro"}

[config]
# Add your assessment config here
max_rows = 5
rit_filter = "WTC"
